name: katana_flutter
description: Package containing a collection of basic Flutter utilities. It provides the base part of the Masamune framework.
version: 0.9.2+5
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_katana_flutter

environment:
  sdk: ">=2.13.0-0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  katana: ^0.9.0
  csv: ^5.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.11
  url_launcher: ^6.0.17
  connectivity_plus: ^2.1.0
  device_info_plus: ^3.2.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  share_plus: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
